name: Matrix workflow

on:
  push:
    branches:
      - main

jobs:
  Matrix-Startegy:
    strategy:
      max-parallel: 2
      matrix:
        java_version: [17,18]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{matrix.os}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{matrix.java_version}}

      - name: Compile Vehicle Project
        run: |
          cd Vehicle
          javac *.java

      - name: Test maven project
        run: |
          cd ..
          cd Maven
          mvn test
        
