name: Matrix workflow

on:
  push:
    branches:
      - main

jobs:
  Matrix-Startegy:
    strategy:
      matrix:
        java_version: [17,18]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - step_name: 'Compile Vehicle Project'
            java_version: 17
            os: ubuntu-latest
          - step_name: 'Test maven project'
            java_version: 18
            os: windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{matrix.java_version}}

      - name: ${{matrix.step_name}}
        run: |
          cd Vehicle
          javac *.java

      - name: ${{matrix.step_name}}
        run: |
          cd Maven
          mvn test
        
