name: Matrix workflowv-2 

on:
  push:
    branches:
      - main

jobs:
  Matrix-Startegy:
    strategy:
      matrix:
        java_version: [17,18]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        exclude:
          - os: ubuntu-latest
            java-version: 17
          - os: macos-latest
            java-version: 18
        include:
          - os: ubuntu-latest
            java-version: 18
            msg: 'Running on ubuntu latest using jdk version 18'
          
    runs-on: ${{matrix.os}}
    env:
      MESSAGE: ${{matrix.msg}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{matrix.java_version}}

      - name: Compile Vehicle project
        run: |
          cd Vehicle
          javac *.java
          echo $MESSAGE
      - name: Test Maven Project
        run: |
          cd Maven
          mvn test
          echo $MESSAGE
      
          
        
